import { groupByState } from '..';
import { BreweryWithRegion } from '../../../../types';

const breweriesInput: BreweryWithRegion[] = [
  {
    id: 'banjo-brewing-fayetteville',
    name: 'Banjo Brewing',
    breweryType: 'planning',
    street: null,
    address2: null,
    address3: null,
    city: 'Fayetteville',
    state: 'West Virginia',
    countyProvince: null,
    postalCode: '25840',
    country: 'United States',
    longitude: '-110',
    latitude: '35',
    region: 'West',
    phone: '3042164231',
    websiteUrl: null,
    updatedAt: '2021-10-23T02:24:55.243Z',
    createdAt: '2021-10-23T02:24:55.243Z',
  },
  {
    id: 'barrel-brothers-brewing-company-windsor',
    name: 'Barrel Brothers Brewing Company',
    breweryType: 'micro',
    street: '399 Business Park Ct Ste 506',
    address2: null,
    address3: null,
    city: 'Windsor',
    state: 'California',
    countyProvince: null,
    postalCode: '95492-6652',
    country: 'United States',
    longitude: '-115',
    latitude: '40',
    region: 'West',
    phone: '7076969487',
    websiteUrl: 'http://www.barrelbrothersbrewing.com',
    updatedAt: '2021-10-23T02:24:55.243Z',
    createdAt: '2021-10-23T02:24:55.243Z',
  },
  {
    id: 'gbc-murrieta',
    name: 'GBC',
    breweryType: 'micro',
    street: '26015 Jefferson Ave Ste D',
    address2: null,
    address3: null,
    city: 'Murrieta',
    state: 'California',
    countyProvince: null,
    postalCode: '92562-6985',
    country: 'United States',
    longitude: '-110',
    latitude: '38',
    region: 'West',
    phone: null,
    websiteUrl: null,
    updatedAt: '2021-10-22T02:24:55.243Z',
    createdAt: '2021-10-22T02:24:55.243Z',
  },
];

const breweriesOutput = {
  'West Virginia': [
    {
      id: 'banjo-brewing-fayetteville',
      name: 'Banjo Brewing',
      breweryType: 'planning',
      street: null,
      address2: null,
      address3: null,
      city: 'Fayetteville',
      state: 'West Virginia',
      countyProvince: null,
      postalCode: '25840',
      country: 'United States',
      longitude: '-110',
      latitude: '35',
      region: 'West',
      phone: '3042164231',
      websiteUrl: null,
      updatedAt: '2021-10-23T02:24:55.243Z',
      createdAt: '2021-10-23T02:24:55.243Z',
    },
  ],

  California: [
    {
      id: 'barrel-brothers-brewing-company-windsor',
      name: 'Barrel Brothers Brewing Company',
      breweryType: 'micro',
      street: '399 Business Park Ct Ste 506',
      address2: null,
      address3: null,
      city: 'Windsor',
      state: 'California',
      countyProvince: null,
      postalCode: '95492-6652',
      country: 'United States',
      longitude: '-115',
      latitude: '40',
      region: 'West',
      phone: '7076969487',
      websiteUrl: 'http://www.barrelbrothersbrewing.com',
      updatedAt: '2021-10-23T02:24:55.243Z',
      createdAt: '2021-10-23T02:24:55.243Z',
    },
    {
      id: 'gbc-murrieta',
      name: 'GBC',
      breweryType: 'micro',
      street: '26015 Jefferson Ave Ste D',
      address2: null,
      address3: null,
      city: 'Murrieta',
      state: 'California',
      countyProvince: null,
      postalCode: '92562-6985',
      country: 'United States',
      longitude: '-110',
      latitude: '38',
      region: 'West',
      phone: null,
      websiteUrl: null,
      updatedAt: '2021-10-22T02:24:55.243Z',
      createdAt: '2021-10-22T02:24:55.243Z',
    },
  ],
};

test('groupByState', () => {
  const result = groupByState(breweriesInput);

  expect(result).toEqual(breweriesOutput);
});
